"""unique constraint email trip_id

Revision ID: 61d72b8deb8b
Revises: f1034aa46b0f
Create Date: 2026-04-30 20:21:05.778831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d72b8deb8b'
down_revision: Union[str, Sequence[str], None] = 'f1034aa46b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('emails_to_invite_email_key'), 'emails_to_invite', type_='unique')
    op.create_unique_constraint('uq_emails_to_invite_email_trip_id', 'emails_to_invite', ['email', 'trip_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_emails_to_invite_email_trip_id', 'emails_to_invite', type_='unique')
    op.create_unique_constraint(op.f('emails_to_invite_email_key'), 'emails_to_invite', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
